configuration:
  error-messages:
    Default: No hemos podido realizar tu operación. Estamos trabajando para solucionar el inconveniente.

  rest-clients:
    contact-data:
      request:
        endpoint: http://${CONTACT_DATA_DOMAIN:localhost:8021}/poc/customer-search/v1/
    pending-orders:
      request:
        endpoint: http://${PENDING_ORDERS_DOMAIN:localhost:8021}/poc/delivery-requests/v1/
    availability:
      request:
        endpoint: http://${AVAILABILITY_DOMAIN:localhost:8021}/poc/delivery-availability/v1/
    reservation:
      request:
        endpoint: http://${AVAILABILITY_DOMAIN:localhost:8021}/poc/delivery-coordination/v1/

quarkus:
  rest-client:
    pending-orders:
      url: ${configuration.rest-clients.pending-orders.request.endpoint}
      verify-host: false
    contact-data:
      url: ${configuration.rest-clients.contact-data.request.endpoint}
      verify-host: false
    availability:
      url: ${configuration.rest-clients.availability.request.endpoint}
      verify-host: false
    reservation:
      url: ${configuration.rest-clients.reservation.request.endpoint}
      verify-host: false