configuration:
  rest-clients:
    contact-data:
      request:
        endpoint: ${CONTACT_DATA_ENDPOINT:http://localhost:8082/poc/customer-search/v1/}
    pending-orders:
      request:
        endpoint: ${PENDING_ORDERS_ENDPOINT:http://localhost:8082/poc/delivery-requests/v1/}
    availability:
      request:
        endpoint: ${AVAILABILITY_ENDPOINT:http://localhost:8082/poc/delivery-availability/v1/}
    reservation:
      request:
        endpoint: ${RESERVATION_ENDPOINT:http://localhost:8082/poc/delivery-coordination/v1/}